version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    working_directory: client
      parallelism: 4
      steps:
        - checkout
        - restore_cache:
            keys:
              - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
              - v2-deps-{{ .Branch }}-
              - v2-deps-
        - run: npm ci
        - save_cache:
            key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            paths:
              - ~/.npm
              - ~/.cache
        - run:
            name: Cypress tests
            command: npm run cypress open
        - store_test_results:
            path: cypress-results
        - store_artifacts:
            path: cypress/videos
        - store_artifacts:
            path: cypress/screenshots