version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  build:
    jobs:
      - cypress/run:
          yarn: true
          no-workspace: true
          working_directory: client
          start: npm start
          wait-on: 'http://localhost:3000'
          post-steps:
            - run: npm start