version: 2

jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm
    working_directory: ~/client
    parallelism: 4
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Running E2E tests with multiple cypress
          command: npm run cypress run
      - store_test_results:
          path: cypress-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots