version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          start: yarn start
          working_directory: client
          record: true
          parallel: true
          parallelism: 4
          wait-on: 'http://localhost:3000'