version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          store_artifacts: true
          yarn: true
          start: yarn start
          working_directory: client
          post-steps:
            - store_artifacts:
                path: cypress-report