export const REQUEST_FETCH_IMAGES = 'REQUEST_FETCH_IMAGES';
export const IMAGES_FETCHED = 'IMAGES_FETCHED';

export const REQUEST_FETCH_USERS = 'REQUEST_FETCH_USERS';
export const USERS_FETCHED = 'USERS_FETCHED';

export const REQUEST_ADD_IMAGE = 'REQUEST_ADD_IMAGE';
export const IMAGE_ADDED = 'IMAGE_ADDED';