export const REQUEST_FETCH_IMAGES = 'REQUEST_FETCH_IMAGES';
export const IMAGES_FETCHED = 'IMAGES_FETCHED';

export const REQUEST_FETCH_USERS = 'REQUEST_FETCH_USERS';
export const USERS_FETCHED = 'USERS_FETCHED';