export const REQUEST_FETCH_IMAGES = 'REQUEST_FETCH_IMAGES';
export const IMAGES_FETCHED = 'IMAGES_FETCHED';

export const REQUEST_FETCH_IMAGES_USER = 'REQUEST_FETCH_IMAGES_USER';
export const USER_IMAGES_FETCHED = 'USER_IMAGES_FETCHED';

export const REQUEST_ADD_IMAGE = 'REQUEST_ADD_IMAGE';
export const IMAGE_ADDED = 'IMAGE_ADDED';

export const REQUEST_FETCH_USERS = 'REQUEST_FETCH_USERS';
export const USERS_FETCHED = 'USERS_FETCHED';

export const REQUEST_FETCH_USER = 'REQUEST_FETCH_USER';
export const USER_FETCHED = 'USER_FETCHED';

export const REQUEST_USER_LOGIN = 'REQUEST_USER_LOGIN';
export const USER_LOGGED = 'USER_LOGGED';
